name: Build Windows Executable

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Build executable
      run: pyinstaller --name=mmrelay.exe --onefile --console main.py

    - name: Install NSIS
      run: |
        $url = 'https://sourceforge.net/projects/nsis/files/NSIS%203/3.06.1/nsis-3.06.1-setup.exe/download'
        $installer = "$env:TEMP\installer.exe"
        Invoke-WebRequest $url -OutFile $installer
        Start-Process -FilePath $installer -ArgumentList '/S' -Wait

    - name: Build NSIS Installer
      run: |
        "C:\Program Files (x86)\NSIS\makensis.exe" installer.nsi
    - name: Compile NSIS script
      run: |
        makensis mmrelay.nsi
  
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mmrelay
        path: |
          dist/mmrelay.exe
          mmrelay-setup.exe
