name: Build Windows Executable

on:
  create:
    tags:
      - v*
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install PyOxidizer
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
          pip install pyoxidizer

      - name: Build Windows Executable
        run: |
          ls -al
          PYOXIDIZER_CONFIG=./pyoxidizer.toml pyoxidizer build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp-windows
          path: build/target/x86_64-pc-windows-msvc/release/myapp.exe
